/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { MetaData, MetaDataInterface } from "../MetaData";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "addr",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "multiHash",
        type: "bytes",
      },
    ],
    name: "MultiHash",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "multiHash",
        type: "bytes",
      },
    ],
    name: "publish",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class MetaData__factory {
  static readonly abi = _abi;
  static createInterface(): MetaDataInterface {
    return new utils.Interface(_abi) as MetaDataInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MetaData {
    return new Contract(address, _abi, signerOrProvider) as MetaData;
  }
}
