/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface MetaDataInterface extends utils.Interface {
  functions: {
    "publish(bytes)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "publish"): FunctionFragment;

  encodeFunctionData(functionFragment: "publish", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "publish", data: BytesLike): Result;

  events: {
    "MultiHash(address,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MultiHash"): EventFragment;
}

export interface MultiHashEventObject {
  addr: string;
  multiHash: string;
}
export type MultiHashEvent = TypedEvent<[string, string], MultiHashEventObject>;

export type MultiHashEventFilter = TypedEventFilter<MultiHashEvent>;

export interface MetaData extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MetaDataInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    publish(
      multiHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  publish(
    multiHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    publish(multiHash: BytesLike, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "MultiHash(address,bytes)"(
      addr?: string | null,
      multiHash?: null
    ): MultiHashEventFilter;
    MultiHash(addr?: string | null, multiHash?: null): MultiHashEventFilter;
  };

  estimateGas: {
    publish(
      multiHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    publish(
      multiHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
